# Generated by Django 4.0 on 2023-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studysolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('applytype', models.CharField(choices=[('Chinese language/Diploma', 'Language'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('Ph.D', 'Phd')], default='Bachelor', max_length=30)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('passport', models.FileField(upload_to='images/file/% Y/% m/% d/')),
                ('photo', models.FileField(upload_to='images/file/% Y/% m/% d/')),
                ('police_clearance', models.FileField(upload_to='images/file/% Y/% m/% d/')),
                ('bank_statement', models.FileField(upload_to='images/file/% Y/% m/% d/')),
                ('stady_plan', models.FileField(upload_to='images/file/% Y/% m/% d/')),
                ('higher_secondary', models.FileField(upload_to='images/file/% Y/% m/% d/')),
                ('other', models.FileField(blank=True, null=True, upload_to='images/file/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
