# Generated by Django 4.0 on 2023-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_emailsubscription_contact_major_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
