# Generated by Django 4.0 on 2023-08-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_emailsubscription_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='major',
        ),
    ]
